# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- test
  

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: one
  jobs:
  - job: get
    pool:
      vmImage: 'ubuntu-latest'
    steps:  
    - script: |
        Date="$(date +'%m/%d/%Y')"
        echo "##vso[task.setvariable variable=Date;isOutput=true]$Date"
      
      name: var
    - bash: |
        echo "$(var.Date)"
        
    
  - job: out
    dependsOn: get
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/heads/master/')))
    variables:
      curdate: $[ dependencies.get.outputs['var.Date'] ]
      SourceBranch: ${Build.SourceBanch}
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "today's date is $(curdate)"
        echo $(SourceBranch)
  
       
