# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: one
  jobs:
  - job: get
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        Date="$(date +'%m/%d/%Y')"
        echo "##vso[task.setvariable variable=Date;isOutput=true]$Date"
      name: var
    - bash: |
        echo "$(var.Date)"
        
- stage: two
  dependsOn: one
  jobs:
  - job: out
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    curdate: $[ dependencies.get.outputs['var.Date'] ]
    steps:
    - script: |
        echo "today's date is $(curdate)"
  
       
